package com.colsubsidio.dotaciones.scheduled.enums;

public enum Parametros {
    PARAMETRO_TIPO_SOLICITUD_MASIVA,
    PARAMETRO_TIPO_SOLICITUD_INCORPORACION,
    PARAMETRO_SOLICITUD_PENDIENTE,
    PARAMETRO_SOLICITUD_RESERVA_FALLIDA,
    PARAMETRO_SOLICITUD_RESERVA_EXITOSA,
    PARAMETRO_SOLICITUD_SALIDA_EXITOSA,
    PARAMETRO_SOLICITUD_SALIDA_FALLIDA
}



